### ISSUE TITLE
Required dependencies not made clear in docs

### ISSUE THREAD

**Issue by mtyzz** [dm3/clojure.java-time#17] opened 2017-12-14 23:29 UTC
The docs for `interval` ([http://dm3.github.io/clojure.java-time/java-time.html#var-interval](url)) do not mention that interval is only accessible if the project using java-time also pulls in java.threeten-extra, leading to a `no-such-var` error when trying to use the library without this undocumented transitive dependency. It would be good if those dependencies were mentioned in the docs.

**Comment by dm3** [comment] 2017-12-18 14:23
Hmm, there's a reference to Threeten-extra - mentioned explicitly before showing the `interval` function in the [README](https://github.com/dm3/clojure.java-time#three-ten-extra). Where would you add the docs to make it more clear?

**Comment by dm3** [comment] 2018-02-14 11:28
Closing due to inactivity

**Comment by AdamClements** [comment] 2020-12-01 11:48
FYI, I found this issue because I was having the exact same issue - looking at the API docs it's not clear at all why interval shouldn't be defined, I went down a rabbit hole checking versions etc before I found this. Maybe just add it to the docstring so it shows up in the api docs?

**Comment by dm3** [comment] 2020-12-01 20:49
Good idea! I'd also love a PR :)

**Comment by dm3** [comment] 2021-03-21 08:16
Duplicate of #54

**Closed by dm3** 2021-03-21 08:16 UTC
Labels: question
