### ISSUE TITLE
Various properties gone missing in 0.3.3

### ISSUE THREAD

**Issue by deepxg** [dm3/clojure.java-time#77] opened 2021-10-03 12:18 UTC
This might be me abusing the API, in which case my apologies, but upgrading from 0.3.2 to 0.3.3 has lost various useful properties and keys I was relying on. For example the property `:minute-of-day` no longer exists, and `as-map` not longer returns `:instant-seconds`. If there are more canonical ways to retrieve these I'd appreciate a pointer!

**Comment by dm3** [comment] 2021-10-03 20:37
Thanks for the report! This is caused by #51. There were no tests checking whether all properties present before the PR remained available afterwards. This is definitely a bug and not something intentional. Please stay on 0.3.2. 

Would also be helpful if you have a list of all the properties that you've relied on. There are two options now:

1. Revert the PR - should be minimal impact as the main goal of the PR - decreasing load time - didn't realize.
2. Add all the properties to the static list manually

Given that I'm not actively working with Clojure anymore, I'm leaning towards 1.

**Comment by unmonoqueteclea** [comment] 2021-10-05 17:20
We also lost two properties:

`:aligned-week-of-year` and :minute-of-hour`

They weren't tested in https://github.com/dm3/clojure.java-time/blob/78cecf35cf959ae83879f655ca8afcde78ce7b92/test/java_time_test.clj#L769

**Comment by orestis** [comment] 2022-02-23 09:42
There doesn't seem to be a 0.3.4 version in clojars? I see a changelog entry that fixes this though.

**Comment by frenchy64** [comment] 2022-06-18 01:52
Fixed by https://github.com/dm3/clojure.java-time/commit/8b1ed78c4c226e12f9a30d2bc50f9c721ee22bb3

Will be in the next release.

**Closed by frenchy64** 2022-06-18 01:52 UTC
Labels: bug

**Comment by brunchboy** [comment] 2022-07-25 03:22
Any idea when the next release might be out? I came here to open an issue about this because I was running into exceptions trying to get the `:minute-of-hour` from a `ZonedDateTime`, but it looks like this will be fixed in the next release already if I am reading this right.

**Comment by frenchy64** [comment] 2022-07-25 03:24
@brunchboy no sorry, waiting on https://github.com/dm3/clojure.java-time/issues/84#issuecomment-1157664090

**Comment by brunchboy** [comment] 2022-07-25 03:26
Ah, that makes sense! Fingers crossed you will get access soon; in the mean time, I will do things the old, Java interop way.
